[project]
name = "oop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mkdeveloper", email = "khubaib.mk@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
oop = "oop:main"
class = "oop.classes:main"
product = "oop.practice.product:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
